# Generated by Django 3.0.14 on 2023-07-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounttypes',
            name='create_date',
        ),
    ]
