# Generated by Django 3.0.14 on 2023-07-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0002_remove_accounttypes_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateitem',
            name='default_rate',
        ),
        migrations.AddField(
            model_name='rateitem',
            name='budget_2w',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='budget_4w',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='default_rate_2w',
            field=models.IntegerField(default=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='default_rate_4w',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='luxury_2w',
            field=models.IntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='luxury_4w',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='premium_2w',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='premium_4w',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rateitem',
            name='suv_4w',
            field=models.IntegerField(default=600),
            preserve_default=False,
        ),
    ]
