# Generated by Django 4.2.3 on 2023-07-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0003_auto_20230711_2207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='free_trail_date_left',
            new_name='free_trial_date_left',
        ),
    ]
