# Generated by Django 4.2.3 on 2023-07-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0005_alter_company_id_alter_companyfeatures_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='free_trial_date_left',
        ),
    ]
