# Generated by Django 4.2.3 on 2023-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0008_alter_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='vehicle_type',
            field=models.IntegerField(),
        ),
    ]
