# Generated by Django 4.2.3 on 2023-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0010_remove_vehicles_make_id_remove_vehicles_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rateitem',
            name='extended_rate_item',
        ),
        migrations.RemoveField(
            model_name='rateitem',
            name='max_quantity',
        ),
        migrations.RemoveField(
            model_name='rateitem',
            name='min_quantity',
        ),
    ]
