# Generated by Django 4.2.3 on 2023-07-13 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0011_remove_rateitem_extended_rate_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='alternate_phone',
        ),
    ]
