# Generated by Django 4.2.3 on 2023-07-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0012_remove_accounts_alternate_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
