# Generated by Django 4.2.3 on 2023-07-17 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0013_alter_company_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='client_version_id',
        ),
    ]
