# Generated by Django 4.2.3 on 2023-07-17 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0014_remove_driverlocation_client_version_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driverlocation',
            table='A2Zbackend_driverlocation',
        ),
    ]
