# Generated by Django 4.2.3 on 2023-07-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0015_alter_driverlocation_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='driverlocation',
            table='a2zbackend_driverlocation',
        ),
    ]
