# Generated by Django 4.2.3 on 2023-07-17 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0016_alter_driverlocation_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlocation',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
