# Generated by Django 4.2.3 on 2023-07-17 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A2Zbackend', '0017_driverlocation_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlocation',
            name='distance',
        ),
        migrations.AlterModelTable(
            name='driverlocation',
            table=None,
        ),
    ]
