# Generated by Django 4.2.3 on 2023-07-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("A2Zbackend", "0018_remove_driverlocation_distance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dispatchentry",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
